### ISSUE TITLE
Documentation error in pip install instructions

### ISSUE THREAD

**Issue by DominicWatson** [jmacul2/sentry-cfml#5]
I was receiving the following error when copying and pasting the pip install instructions from your readme:

```
error: RPC failed; result=22, HTTP code = 405
```

Took me a while to figure out that the github URL was using http rather than https. Using https fixed the issue for me. So:

```
$ pip install -e git+https://github.com/jmacul2/sentry-cfml.git#egg=sentry_cfml-dev
```

**Comment by jmacul2** [comment]
fixed....thanks.
